apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstore
  name: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - image: "soloio/bookstore:v0.1"
        imagePullPolicy: IfNotPresent
        name: bookstore
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookstore
  name: bookstore
spec:
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
  selector:
    app: bookstore
