changelog:
  - type: NON_USER_FACING
    description: Add docs indicating the Helm value to set when enabling health checks on Envoy.
    issueLink: https://github.com/solo-io/gloo/issues/3114
  - type: HELM
    description: >
      In "gateway" installations of Gloo, enable configuration of the loopback address used for binding the Envoy admin port. This is controlled through the new Helm
      string value `gatewayProxies.gatewayProxy.loopBackAddress`. That same Helm value is also now used to configure the address
      used for Envoy's readiness probes in a Kubernetes environment. In "ingress" installations of Gloo, Envoy's
      admin port address is configured using the Helm string value `ingressProxy.loopBackAddress`. And in "knative" installations,
      it is configured using the Helm string value `settings.integrations.knative.proxy.loopBackAddress`.
    issueLink: https://github.com/solo-io/gloo/issues/3114
