{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ .Values.ingressProxy.label }}
  name: ingress-proxy
  namespace: {{ .Release.Namespace }}
{{- if .Values.ingressProxy.service }}
{{- if .Values.ingressProxy.service.extraAnnotations }}
  annotations:
  {{- range $key, $value := .Values.ingressProxy.service.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
spec:
  ports:
  - port: {{ .Values.ingressProxy.service.httpPort }}
    targetPort: {{ .Values.ingressProxy.deployment.httpPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.ingressProxy.service.httpsPort }}
    targetPort: {{ .Values.ingressProxy.deployment.httpsPort }}
    protocol: TCP
    name: https
  selector:
    gloo: ingress-proxy
  type: {{ .Values.ingressProxy.service.type }}
  {{- if and (eq .Values.ingressProxy.service.type "LoadBalancer") .Values.ingressProxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.ingressProxy.service.loadBalancerIP }}
  {{- end }}
{{- end }}
