apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.gloo.serviceAccount.extraAnnotations }}
  annotations:
    {{- range $key, $value := .Values.gloo.serviceAccount.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app: gloo
    gloo: gloo
  name: gloo
  namespace: {{ $.Release.Namespace }}
{{- if .Values.gloo.serviceAccount.disableAutomount }}
automountServiceAccountToken: false
{{ end }}