apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gloo
  name: gloo
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.gloo.deployment.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.gloo.deployment.externalTrafficPolicy }}
{{- end }}
  ports:
  - name: grpc-xds
    port: {{ .Values.gloo.deployment.xdsPort }}
    protocol: TCP
  - name: rest-xds
    port: {{ .Values.gloo.deployment.restXdsPort }}
    protocol: TCP
  - name: grpc-validation
    port: {{ .Values.gloo.deployment.validationPort }}
    protocol: TCP
  - name: metrics-grpc
    port: 9966
    protocol: TCP
  - name: wasm-cache
    port: 9979
    protocol: TCP
  selector:
    gloo: gloo
