{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.gateway.serviceAccount.extraAnnotations }}
  annotations:
    {{- range $key, $value := .Values.gateway.serviceAccount.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app: gloo
    gloo: gateway
  name: gateway
  namespace: {{ $.Release.Namespace }}
{{- if .Values.gateway.serviceAccount.disableAutomount }}
automountServiceAccountToken: false
{{ end }}
{{ end }}
