{{- if and .Values.gateway.enabled .Values.accessLogger.enabled }}
{{- $image := .Values.accessLogger.image }}
{{- $statsConfig := coalesce .Values.accessLogger.stats .Values.global.glooStats -}}
{{- if .Values.global }}
{{- $image = merge .Values.accessLogger.image .Values.global.image }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy-access-logger
  name: gateway-proxy-access-logger
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ .Values.accessLogger.replicas }}
  selector:
    matchLabels:
      app: gloo
      gloo: gateway-proxy-access-logger
  template:
    metadata:
      labels:
        app: gloo
        gloo: gateway-proxy-access-logger
        {{- if .Values.accessLogger.extraAccessLoggerLabels }}
        {{- range $key, $value := .Values.accessLogger.extraAccessLoggerLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- if $statsConfig.enabled }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
      serviceAccountName: gateway-proxy
      securityContext:
        runAsNonRoot: true
        {{- if not .Values.accessLogger.floatingUserId }}
        runAsUser: {{ printf "%.0f" (float64 .Values.accessLogger.runAsUser) -}}
        {{- end }}
      containers:
        - image: {{ template "gloo.image" $image }}
          imagePullPolicy: {{ $image.pullPolicy }}
          name: access-logger
{{- if .Values.accessLogger.resources }}
          resources:
{{ toYaml .Values.accessLogger.resources | indent 12}}
{{- end}}
          env:
{{- if .Values.accessLogger.customEnv }}
{{ toYaml .Values.accessLogger.customEnv | indent 10 }}
{{- end }}
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
{{- if .Values.accessLogger.serviceName }}
          - name: SERVICE_NAME
            value: {{.Values.accessLogger.serviceName}}
{{- end }} # if .Values.accessLogger.serviceName
          - name: SERVER_PORT
            value: "{{ .Values.accessLogger.port }}"
          ports:
          - containerPort: {{ .Values.accessLogger.port }}
            name: http
            protocol: TCP
{{- end }}