{{- if .Values.gateway.enabled }}
{{- range $name, $spec := .Values.gatewayProxies }}
{{- $svcName := default $name $spec.service.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: {{ $name | kebabcase }}
  name: {{ $svcName | kebabcase }}
  namespace: {{ $.Release.Namespace }}
{{- if $spec.service.extraAnnotations }}
  annotations:
  {{- range $key, $value := $spec.service.extraAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
{{- if $spec.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $spec.service.externalTrafficPolicy }}
{{- end }}
  ports:
{{- if $spec.service.httpsFirst }}
  - port: {{ $spec.service.httpsPort }}
    targetPort: {{ $spec.podTemplate.httpsPort }}
    protocol: TCP
    name: https
    {{- if and (eq $spec.service.type "NodePort") $spec.service.httpsNodePort }}
    nodePort: {{ $spec.service.httpsNodePort }}
    {{- end}}
  - port: {{ $spec.service.httpPort }}
    targetPort: {{ $spec.podTemplate.httpPort }}
    protocol: TCP
    name: http
    {{- if and (eq $spec.service.type "NodePort") $spec.service.httpNodePort }}
    nodePort: {{ $spec.service.httpNodePort }}
    {{- end}}
{{- else }}
  - port: {{ $spec.service.httpPort }}
    targetPort: {{ $spec.podTemplate.httpPort }}
    protocol: TCP
    name: http
    {{- if and (eq $spec.service.type "NodePort") $spec.service.httpNodePort }}
    nodePort: {{ $spec.service.httpNodePort }}
    {{- end}}
  - port: {{ $spec.service.httpsPort }}
    targetPort: {{ $spec.podTemplate.httpsPort }}
    protocol: TCP
    name: https
    {{- if and (eq $spec.service.type "NodePort") $spec.service.httpsNodePort }}
    nodePort: {{ $spec.service.httpsNodePort }}
    {{- end}}
{{- end }}
  selector:
    gateway-proxy-id: {{ $name | kebabcase }}
    gateway-proxy: live
  type: {{ $spec.service.type }}
  {{- if and (eq $spec.service.type "ClusterIP") $spec.service.clusterIP }}
  clusterIP: {{ $spec.service.clusterIP }}
  {{- end }}
  {{- if eq $spec.service.type "LoadBalancer" }}
  {{- if $spec.service.loadBalancerIP }}
  loadBalancerIP: {{ $spec.service.loadBalancerIP }}
  {{- end }} # $spec.service.loadBalancerIP
  {{- if $spec.service.loadBalancerSourceRanges }}
  {{- with $spec.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }} # with spec.service.loadBalancerSourceRanges
  {{- end }} # $spec.service.loadBalancerSourceRanges
  {{- end }} # $spec.service.type "LoadBalancer"
{{- end }}
{{ end }}