changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo/issues/4293
    resolvesIssue: false
    description: >
      Config can be passed in to the passthrough auth grpc service through AuthConfig.