changelog:
  - type: HELM
    issueLink: https://github.com/solo-io/gloo/issues/3747
    description: >
      Panic mode allows Envoy load balancing to disregard host's health status.
  - type: NON_USER_FACING
    issueLink: https://github.com/solo-io/gloo/issues/3747
    description: >
      Disable panic mode for e2e and kube2e tests.
      With panic mode disabled, we can be more certain that our tests are validating healthy hosts properly.