namespace:
  create: false
k8s:
  clusterName: cluster.local
settings:
  # if this is set to false, default settings will be created by pods upon boot
  create: true
  linkerd: false
  enableRestEds: false
  aws: {}
  invalidConfigPolicy:
    replaceInvalidRoutes: false
    invalidRouteResponseCode: 404
    invalidRouteResponseBody: 'Gloo Gateway has invalid configuration. Administrators should run `glooctl check` to find and fix config errors.'
  integrations:
    knative:
      enabled: false
      version: "0.10.0"
      proxy:
        loopBackAddress: 127.0.0.1
        image:
          repository: gloo-envoy-wrapper
        httpPort: 8080
        httpsPort: 8443
        replicas: 1
        service:
          type: LoadBalancer
          extraAnnotations: {}
          httpPort: 80
          httpsPort: 443
  # Namespaces that Gloo should watch. This includes watches set for pods, services, as well as CRD configuration objects.
  watchNamespaces: []
  # Gloo allows you to directly reference a Kubernetes service as a routing destination. To enable this feature,
  # Gloo scans the cluster for Kubernetes services and creates a special type of in-memory Upstream to represent them.
  # If the cluster contains a lot of services and you do not restrict the namespaces Gloo is watching, this can result
  # in significant overhead. If you do not plan on using this feature, you can set this flag to true to turn it off.
  disableKubernetesDestinations: false
  # Set this option to determine the state of an Envoy listener when the corresponding Gloo Proxy resource has no routes.
  # If false (default), Gloo will propagate the state of the Proxy to Envoy, resetting the listener to a clean slate with no routes.
  # If true, Gloo will keep serving the routes from the last applied valid configuration.
  disableProxyGarbageCollection: false
gloo:
  deployment:
    image:
      repository: gloo
    xdsPort: 9977
    restXdsPort: 9976
    validationPort: 9988
    replicas: 1
    runAsUser: 10101
    serviceAccount: {}
discovery:
  enabled: true
  fdsMode: WHITELIST
  serviceAccount: {}
  deployment:
    image:
      repository: discovery
    replicas: 1
    runAsUser: 10101
    enablePodSecurityContext: true
    fsGroup: 10101
gateway:
  enabled: true
  readGatewaysFromAllNamespaces: false
  validation:
    enabled: true
    failurePolicy: "Ignore"
    secretName: gateway-validation-certs
    alwaysAcceptResources: true
    allowWarnings: true
    disableTransformationValidation: false
    warnRouteShortCircuiting: false
    webhook:
      enabled: true
      disableHelmHook: false
      extraAnnotations: {}
  deployment:
    image:
      repository: gateway
    replicas: 1
    runAsUser: 10101
  certGenJob:
    enabled: true
    image:
      repository: certgen
    restartPolicy: OnFailure
    setTtlAfterFinished: true
    ttlSecondsAfterFinished: 60
    runAsUser: 10101
  proxyServiceAccount: {}
  serviceAccount: {}
gatewayProxies:
  gatewayProxy:
    envoyApiVersion: V3
    gatewaySettings:
      useProxyProto: false
    failover:
      enabled: false
      port: 15443
      secretName: failover-downstream
    kind:
      deployment:
        replicas: 1
    podTemplate:
      probes: false
      image:
        repository: gloo-envoy-wrapper
      httpPort: 8080
      httpsPort: 8443
      runAsUser: 10101
      enablePodSecurityContext: true
      fsGroup: 10101
      runUnprivileged: true
      disableNetBind: true
      gracefulShutdown:
        enabled: false
        sleepTimeSeconds: 25
      customReadinessProbe: {}
    service:
      customPorts: []
      type: LoadBalancer
      # clusterIP: None
      httpPort: 80
      httpsPort: 443
    # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
    # extraAnnotations:
    #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT
    tracing:
    configMap:
      data:
    loopBackAddress: 127.0.0.1
    globalDownstreamMaxConnections: 250000
    healthyPanicThreshold: 50
accessLogger:
  enabled: false
  port: 8083
  serviceName: AccessLog
  image:
    repository: access-logger
  runAsUser: 10101
  replicas: 1
  stats:
    enabled: true
ingress:
  enabled: false
  deployment:
    image:
      repository: ingress
    replicas: 1
    runAsUser: 10101
ingressProxy:
  # Set to a unique value to allow using several ingress proxy instances in the same cluster.
  label: ingress-proxy
  loopBackAddress: 127.0.0.1
  deployment:
    image:
      repository: gloo-envoy-wrapper
    httpPort: 8080
    httpsPort: 8443
    replicas: 1
  service:
    type: LoadBalancer
    extraAnnotations: {}
    httpPort: 80
    httpsPort: 443
  configMap:
    data:
  tracing:
global:
  image:
    registry: quay.io/solo-io
    pullPolicy: IfNotPresent
    extended: false
  glooRbac:
    create: true
    namespaced: false
  glooStats:
    enabled: true
    routePrefixRewrite: /stats/prometheus
  glooMtls:
    enabled: false
    sds:
      image:
        repository: sds
    envoy:
      image:
        repository: gloo-envoy-wrapper
  istioSDS:
    enabled: false
  istioIntegration:
    labelInstallNamespace: false
    whitelistDiscovery: false
    disableAutoinjection: false
  # AddEnterpriseSettings and extauthCustomYaml control differences in the settings manifest between open source and enterprise
  AddEnterpriseSettings: false
  extauthCustomYaml: true