changelog:
  - type: NON_USER_FACING
    issueLink: https://github.com/solo-io/gloo/issues/4329
    description: >
      Allows configuration of query parameters to add the the Gloo extauth service's OIDC token request. This can be
      useful as part of OIDC PKCE to set the `code_verifier`. This PR adds the server-side config that was forgotten
      in https://github.com/solo-io/gloo/pull/4649.
    resolvesIssue: false