changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo/issues/3879
    resolvesIssue: false
    description:  >
      Add API to support optional OIDC configuration override for ext-auth. OIDC Configuration is discovered at
      <issuerUrl>/.well-known/openid-configuration and this configuration can override those discovered values.