apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-latest
  labels:
    app: gloo-docs
    version: latest
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: latest

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-latest
  labels:
    app: gloo-docs
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: latest
  template:
    metadata:
      labels:
        app: gloo-docs
        version: latest
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:current"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-1-3-0
  labels:
    app: gloo-docs
    version: 1-3-0
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: 1-3-0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-1-3-0
  labels:
    app: gloo-docs
    version: 1-3-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: 1-3-0
  template:
    metadata:
      labels:
        app: gloo-docs
        version: 1-3-0
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:1.3.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-1-2-0
  labels:
    app: gloo-docs
    version: 1-2-0
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: 1-2-0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-1-2-0
  labels:
    app: gloo-docs
    version: 1-2-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: 1-2-0
  template:
    metadata:
      labels:
        app: gloo-docs
        version: 1-2-0
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:1.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-1-1-0
  labels:
    app: gloo-docs
    version: 1-1-0
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: 1-1-0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-1-1-0
  labels:
    app: gloo-docs
    version: 1-1-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: 1-1-0
  template:
    metadata:
      labels:
        app: gloo-docs
        version: 1-1-0
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:1.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-1-0-0
  labels:
    app: gloo-docs
    version: 1-0-0
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: 1-0-0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-1-0-0
  labels:
    app: gloo-docs
    version: 1-0-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: 1-0-0
  template:
    metadata:
      labels:
        app: gloo-docs
        version: 1-0-0
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-0-21-3
  labels:
    app: gloo-docs
    version: 0-21-3
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: 0-21-3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-0-21-3
  labels:
    app: gloo-docs
    version: 0-21-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: 0-21-3
  template:
    metadata:
      labels:
        app: gloo-docs
        version: 0-21-3
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:0-21-3"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  namespace: docs
  name: gloo-docs-0-20-13
  labels:
    app: gloo-docs
    version: 0-20-13
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gloo-docs
    version: 0-20-13

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docs
  name: gloo-docs-0-20-13
  labels:
    app: gloo-docs
    version: 0-20-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloo-docs
      version: 0-20-13
  template:
    metadata:
      labels:
        app: gloo-docs
        version: 0-20-13
    spec:
      containers:
        - name: gloo-docs
          image: "gcr.io/solo-public/gloo-docs:0-20-13"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: docsmgmt
  namespace: docs
spec:
  displayName: docsmgmt
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /gloo/latest
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-latest-80
            namespace: gloo-system
    - matchers:
      - prefix: /gloo/1.3.0/
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-1-3-0-80
            namespace: gloo-system
    - matchers:
      - prefix: /gloo/1.2.0/
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-1-2-0-80
            namespace: gloo-system
    - matchers:
        - prefix: /gloo/1.1.0/
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-1-1-0-80
            namespace: gloo-system
    - matchers:
        - prefix: /gloo/1.0.0/
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-1-0-0-80
            namespace: gloo-system
    - matchers:
        - prefix: /gloo/0.21.3/
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-0-21-3-80
            namespace: gloo-system
      options:
        prefixRewrite: /gloo/0-21-3/
    - matchers:
      - prefix: /gloo/0.20.13/
      options:
        prefixRewrite: /gloo/0-20-13/
      routeAction:
        single:
          upstream:
            name: docs-gloo-docs-0-20-13-80
            namespace: gloo-system
